copyright: Copyright &copy; 2023 SOTAI Labs Inc.
site_name: PyTorch Lattice
repo_name: pytorch-lattice
repo_url: https://github.com/ControlAI/pytorch-lattice/
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotation
    - content.code.copy
    - content.code.link
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: blue-grey
      accent: deep-orange
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: blue-grey
      accent: deep-orange
  font:
    text: Roboto
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ControlAI
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/WilliamBakst
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/wbakst/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Get Started:
      - Welcome to PyTorch Lattice: "index.md"
      - Why use PyTorch Lattice: "why.md"
      - Installation: "installation.md"
      - Quickstart: "quickstart.md"
      - Contributing: "contributing.md"
      - How to help us!: "help.md"
      - Changelog: "changelog.md"
  - Concepts:
      - Placeholder: "placeholder.md"
  - Walkthroughs:
      - Placeholder: "placeholder.md"
  - API Reference:
      - Placeholder: "placeholder.md"
