name: Lint
run-name: ${{ github.actor }} is linting the package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Ruff
        uses: chartboost/ruff-action@v1

      - name: Install and run mypy
        run: pip install mypy

      - name: Run mypy
        run: python -m mypy .
